"""Container backend for the Mini-Android Container (MAC).

The package originally used LXC directly.  This checkout also ships the
``shadow-droid-core`` namespace runner, so the Python UI uses LXC when it is
installed and transparently falls back to the local core binary otherwise.
"""

from __future__ import annotations

import argparse
import logging
import os
import shlex
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Dict, List, Optional

from aerodroid.config import Defaults, Paths

logger = logging.getLogger(__name__)


class LXCError(Exception):
    pass


class LXCContainer:
    """Manage a privileged Android container.

    Public method names are kept for compatibility with the existing UI.  When
    LXC tools are unavailable the implementation delegates to ``shadow-droid-core``.
    """

    def __init__(
        self,
        name: str = Defaults.CONTAINER_NAME,
        rootfs: Optional[Path] = None,
        memory_mb: int = Defaults.MEMORY_LIMIT_MB,
        cpu_shares: int = Defaults.CPU_SHARES,
        cpu_quota_micros: int = Defaults.CPU_QUOTA_MICROS,
        cpu_period_micros: int = Defaults.CPU_PERIOD_MICROS,
        pids_max: int = Defaults.PIDS_MAX,
    ):
        self.name = name
        self.rootfs = Path(rootfs) if rootfs else Paths.ROOTFS_DIR
        self.memory_mb = memory_mb
        self.cpu_shares = cpu_shares
        self.cpu_quota_micros = cpu_quota_micros
        self.cpu_period_micros = cpu_period_micros
        self.pids_max = pids_max
        self.config_path = Paths.CONTAINER_DIR / "config"
        self.core_path = Paths.CORE_BINARY
        self.cgroup_path = Path("/sys/fs/cgroup/phishadowd") / self.name
        self._process: Optional[subprocess.Popen] = None
        self.backend = self._select_backend()

    def _select_backend(self) -> str:
        if self._has_lxc():
            return "lxc"
        if self.core_path.exists() and os.access(self.core_path, os.X_OK):
            return "core"
        return "unavailable"

    @staticmethod
    def _require_executable(cmd: str) -> str:
        which = shutil.which(cmd)
        if not which:
            raise LXCError(f"Required command '{cmd}' not found in PATH")
        return which

    @staticmethod
    def _has_lxc() -> bool:
        return all(shutil.which(cmd) for cmd in ("lxc-start", "lxc-stop", "lxc-info", "lxc-attach"))

    def exists(self) -> bool:
        if self.backend == "lxc":
            return self.config_path.exists()
        if self.backend == "core":
            return self.core_path.exists() and self.rootfs.exists()
        return False

    def create_config(self) -> None:
        """Write a minimal LXC configuration for Android."""
        if self.backend == "core":
            self._validate_core_runtime()
            return
        if self.backend == "unavailable":
            raise LXCError("No supported runtime found: install LXC or build bin/shadow-droid-core")

        Paths.CONTAINER_DIR.mkdir(parents=True, exist_ok=True)
        if not self.rootfs.exists():
            raise LXCError(f"Rootfs not found: {self.rootfs}")

        wayland_sock = self._wayland_socket()
        runtime_dir = str(Paths.XDG_RUNTIME_DIR)
        uid = os.getuid()
        shared_dir = Path("/home/dang-nhat-phi/AeroAPK/shared")
        shared_dir.mkdir(parents=True, exist_ok=True)
        try:
            shared_dir.chmod(0o777)
        except Exception:
            pass

        lines: List[str] = [
            "# Auto-generated by AeroDroid",
            f"lxc.uts.name = {Defaults.HOSTNAME}",
            "lxc.arch = x86_64",
            "",
            "# Base LXC configuration",
            "lxc.include = /usr/share/lxc/config/common.conf",
            "",
            "# Rootfs",
            f"lxc.rootfs.path = {self.rootfs}",
            "lxc.mount.auto = proc:mixed sys:mixed cgroup:mixed",
            "",
            "# Device access",
            "lxc.cgroup2.devices.allow = c 10:232 rwm  # binder",
            "lxc.cgroup2.devices.allow = c 10:200 rwm  # tun",
            "lxc.mount.entry = /dev/dri dev/dri none bind,optional,create=dir 0 0",
            "lxc.mount.entry = /dev/binderfs dev/binderfs none bind,optional,create=dir 0 0",
            f"lxc.mount.entry = {runtime_dir} run/user/{uid} none bind,optional,create=dir 0 0",
            f"lxc.mount.entry = {shared_dir} data/media/0/Download none bind,create=dir 0 0",
            "",
            "# Graphics passthrough",
            f"lxc.mount.entry = {wayland_sock} run/user/{uid}/wayland-0 none bind,optional,create=file 0 0",
            "lxc.environment = WAYLAND_DISPLAY=wayland-0",
            f"lxc.environment = XDG_RUNTIME_DIR={runtime_dir}",
            "lxc.environment = container=aerodroid",
            "",
            "# Resource limits (cgroup v2)",
            f"lxc.cgroup2.memory.max = {self.memory_mb}M",
            f"lxc.cgroup2.cpu.weight = {self.cpu_shares}",
            f"lxc.cgroup2.cpu.max = {self.cpu_quota_micros} {self.cpu_period_micros}",
            f"lxc.cgroup2.pids.max = {self.pids_max}",
            "",
            "# Init command",
            "lxc.init.cmd = /init",
            "",
            "# Logging",
            f"lxc.log.file = {Paths.CONTAINER_DIR}/container.log",
            "lxc.log.level = 1",
        ]

        self.config_path.write_text("\n".join(lines))
        logger.info("Wrote LXC config to %s", self.config_path)

    def start(self, wait: bool = True) -> None:
        if self.backend == "core":
            self._start_core(wait=wait)
            return
        if self.backend == "unavailable":
            raise LXCError("No supported runtime found: install LXC or build bin/shadow-droid-core")

        if not self.exists():
            self.create_config()
        if self.is_running():
            logger.info("Container %s is already running", self.name)
            return
        self._run(["lxc-start", "-n", self.name, "-d", "-P", str(Paths.SYSTEM_LIB)])
        if wait:
            self._wait_for_state("RUNNING", timeout=30)
        logger.info("Container %s started", self.name)

    def stop(self, timeout: int = 10) -> None:
        if self.backend == "core":
            self._stop_core()
            return
        if self.backend == "unavailable":
            return

        if not self.is_running():
            return
        self._run(["lxc-stop", "-n", self.name, "-t", str(timeout), "-P", str(Paths.SYSTEM_LIB)])
        logger.info("Container %s stopped", self.name)

    def status(self) -> Dict[str, str]:
        if self.backend == "core":
            return self._core_status()
        if self.backend == "unavailable":
            return {"name": self.name, "state": "UNAVAILABLE", "backend": "none"}

        result: Dict[str, str] = {"name": self.name, "state": "UNKNOWN"}
        try:
            out = self._run(
                ["lxc-info", "-n", self.name, "-s", "-p", "-P", str(Paths.SYSTEM_LIB)],
                check=False,
                capture_output=True,
                text=True,
            )
            for line in out.stdout.splitlines():
                if ":" in line:
                    key, value = line.split(":", 1)
                    result[key.strip().lower()] = value.strip()
        except Exception as exc:  # pragma: no cover
            logger.debug("lxc-info failed: %s", exc)
        result["backend"] = "lxc"
        return result

    def is_running(self) -> bool:
        return self.status().get("state") == "RUNNING"

    def attach(self, cmd: List[str]) -> subprocess.CompletedProcess:
        """Run a command inside the running container."""
        if not self.is_running():
            raise LXCError("Container is not running")
        if self.backend == "core":
            full = self._core_cmd("exec", "--name", self.name, "--", *cmd)
            return self._run(full, check=False, capture_output=True, text=True)
        full = ["lxc-attach", "-n", self.name, "-P", str(Paths.SYSTEM_LIB), "--"] + cmd
        return self._run(full, check=False, capture_output=True, text=True)

    def getprop(self, name: str) -> str:
        """Read an Android system property from inside the container."""
        result = self.attach(["/system/bin/getprop", name])
        if result.returncode != 0:
            return ""
        return (result.stdout or "").strip()

    def android_framework_ready(self) -> tuple[bool, str]:
        if self.backend != "core":
            return self.is_running(), "container is not running"

        missing: list[str] = []
        details: list[str] = []
        for service in ("activity", "package", "mount"):
            result = self._run(
                self._core_cmd("exec", "--name", self.name, "--", "/system/bin/service", "check", service),
                check=False,
                capture_output=True,
                text=True,
                timeout=2,
            )
            output = (result.stdout or result.stderr or "").strip()
            if result.returncode != 0 or ": found" not in output:
                missing.append(service)
                details.append(f"{service}={output or 'no response'}")

        boot = self._run(
            self._core_cmd("exec", "--name", self.name, "--", "/system/bin/getprop", "sys.boot_completed"),
            check=False,
            capture_output=True,
            text=True,
            timeout=2,
        )
        boot_completed = (boot.stdout or "").strip()
        if boot_completed != "1":
            missing.append("sys.boot_completed")
            details.append(f"sys.boot_completed={boot_completed or 'empty'}")

        if missing:
            return False, "; ".join(details)
        return True, "ready"

    def install_apk_inside(self, apk_path: Path) -> subprocess.CompletedProcess:
        if self.backend == "core":
            cmd = self._core_cmd("install", "--name", self.name, str(apk_path))
            return self._run(cmd, check=False, capture_output=True, text=True, timeout=200)
        return self.attach(["/system/bin/pm", "install", "-r", str(apk_path)])

    def uninstall_app_inside(self, package_name: str) -> subprocess.CompletedProcess:
        if self.backend == "core":
            cmd = self._core_cmd("uninstall", "--name", self.name, package_name)
            return self._run(cmd, check=False, capture_output=True, text=True, timeout=90)
        return self.attach(["/system/bin/pm", "uninstall", package_name])

    def launch_app(self, package_name: str, activity: Optional[str] = None) -> subprocess.CompletedProcess:
        if self.backend == "core":
            args = ["launch", "--name", self.name, "--package", package_name]
            if activity:
                args.extend(["--activity", activity])
            cmd = self._core_cmd(*args)
            return self._run(cmd, check=False, capture_output=True, text=True, timeout=90)

        self.attach(["/system/bin/setprop", "waydroid.active_apps", package_name])
        if activity:
            component = f"{package_name}/{activity}"
            return self.attach([
                "/system/bin/am", "start",
                "-a", "android.intent.action.MAIN",
                "-c", "android.intent.category.LAUNCHER",
                "-n", component,
            ])
        return self.attach([
            "/system/bin/monkey",
            "-p", package_name,
            "-c", "android.intent.category.LAUNCHER",
            "1",
        ])

    def launch_desktop(self) -> subprocess.CompletedProcess:
        self.attach(["/system/bin/setprop", "waydroid.active_apps", ""])
        return self.attach([
            "/system/bin/am", "start",
            "-a", "android.intent.action.MAIN",
            "-c", "android.intent.category.HOME",
        ])

    def _wait_for_state(self, desired: str, timeout: int) -> None:
        deadline = time.time() + timeout
        while time.time() < deadline:
            if self.status().get("state") == desired:
                return
            time.sleep(0.25)
        raise LXCError(f"Container did not reach {desired} state within {timeout}s")

    def _validate_core_runtime(self) -> None:
        if not self.core_path.exists():
            raise LXCError(f"Runtime binary not found: {self.core_path}")
        if not os.access(self.core_path, os.X_OK):
            raise LXCError(f"Runtime binary is not executable: {self.core_path}")
        if not self.rootfs.exists():
            raise LXCError(f"Rootfs not found: {self.rootfs}")
        if not (self.rootfs / "init").exists() and not (self.rootfs / "system" / "bin" / "init").exists():
            raise LXCError(f"Rootfs does not look bootable: {self.rootfs}")

    def _start_core(self, wait: bool) -> None:
        self._validate_core_runtime()
        if self.is_running():
            logger.info("Container %s is already running", self.name)
            return

        Paths.AERODROID_DATA.mkdir(parents=True, exist_ok=True)
        Paths.CORE_STATE_DIR.mkdir(parents=True, exist_ok=True)
        log_path = Paths.AERODROID_DATA / "shadow-droid-core.log"
        log_file = open(log_path, "ab", buffering=0)
        display_mode = os.environ.get("AERODROID_DISPLAY_MODE", "auto").strip() or "auto"
        cmd = self._core_cmd(
            "run",
            "--name", self.name,
            "--rootfs", str(self.rootfs),
            "--state-dir", str(Paths.CORE_STATE_DIR),
            "--display-mode", display_mode,
            "--memory", f"{self.memory_mb}M",
            "--cpu-quota", str(self.cpu_quota_micros),
            "--cpu-period", str(self.cpu_period_micros),
            "--pids-max", str(self.pids_max),
        )
        logger.info("Starting core runtime: %s", shlex.join(cmd))
        # The Go runtime owns display setup. On GNOME Wayland, auto mode starts
        # a nested Weston Wayland compositor and gives Android that private
        # socket, avoiding Mutter-direct hwcomposer disconnects.
        env = os.environ.copy()
        try:
            self._process = subprocess.Popen(
                cmd,
                stdin=subprocess.DEVNULL,
                stdout=log_file,
                stderr=subprocess.STDOUT,
                start_new_session=True,
                env=env,
            )
        except Exception:
            log_file.close()
            raise
        else:
            log_file.close()

        if wait:
            deadline = time.time() + 180  # Android needs up to 3 min to boot
            boot_ready = False
            while time.time() < deadline:
                if self._process.poll() is not None:
                    raise LXCError(f"Runtime exited early; see {log_path}")
                ready, detail = self.android_framework_ready()
                if ready:
                    boot_ready = True
                    break
                time.sleep(3)
            if not boot_ready:
                raise LXCError(
                    f"Android framework not ready after 3 minutes; see {log_path}")
        logger.info("Core container %s started", self.name)

    def _stop_core(self) -> None:
        if not self.cgroup_path.exists() and (self._process is None or self._process.poll() is not None):
            return
        cmd = self._core_cmd("stop", "--name", self.name)
        result = self._run(cmd, check=False, capture_output=True, text=True)
        if result.returncode != 0:
            stderr = (result.stderr or result.stdout or "").strip()
            raise LXCError(f"Stop failed: {stderr}")
        if self._process and self._process.poll() is None:
            try:
                self._process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self._process.kill()

    def _core_status(self) -> Dict[str, str]:
        result = {"name": self.name, "state": "STOPPED", "backend": "core"}
        try:
            pid = self._core_pid()
        except LXCError as exc:
            result["error"] = str(exc)
            return result
        result["state"] = "RUNNING"
        result["pid"] = pid
        return result

    def _core_pid(self) -> str:
        procs_file = self.cgroup_path / "cgroup.procs"
        try:
            data = procs_file.read_text()
        except FileNotFoundError as exc:
            raise LXCError(f"Container is not running: {self.name}") from exc
        except PermissionError as exc:
            raise LXCError(f"Cannot read {procs_file}; root privileges may be required") from exc

        for line in data.splitlines():
            pid = line.strip()
            if pid:
                return pid
        raise LXCError(f"Container has no processes: {self.name}")

    def _core_cmd(self, *args: str) -> List[str]:
        return [str(self.core_path), *args]

    @staticmethod
    def _run(
        cmd: List[str],
        *,
        check: bool = True,
        capture_output: bool = False,
        text: bool = True,
        timeout: Optional[float] = None,
    ) -> subprocess.CompletedProcess:
        logger.debug("Running: %s", shlex.join(cmd))
        try:
            result = subprocess.run(cmd, check=False, capture_output=capture_output, text=text, timeout=timeout)
        except subprocess.TimeoutExpired as exc:
            raise LXCError(f"Command timed out after {timeout:g}s: {shlex.join(cmd)}") from exc
        if check and result.returncode != 0:
            stderr = (result.stderr or "").strip()
            raise LXCError(f"Command failed ({result.returncode}): {shlex.join(cmd)}\n{stderr}")
        return result

    @staticmethod
    def _wayland_socket() -> str:
        return str(Paths.XDG_RUNTIME_DIR / Defaults.WAYLAND_SOCKET)


def cli() -> int:
    parser = argparse.ArgumentParser(description="AeroDroid LXC container backend")
    parser.add_argument("action", choices=["create", "start", "stop", "status", "attach"])
    parser.add_argument("--rootfs", type=Path, default=None)
    parser.add_argument("--memory", type=int, default=Defaults.MEMORY_LIMIT_MB)
    parser.add_argument("--cpu-quota", type=int, default=Defaults.CPU_QUOTA_MICROS)
    parser.add_argument("--cpu-period", type=int, default=Defaults.CPU_PERIOD_MICROS)
    parser.add_argument("--command", default="/system/bin/sh", help="for attach action")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    container = LXCContainer(
        rootfs=args.rootfs,
        memory_mb=args.memory,
        cpu_quota_micros=args.cpu_quota,
        cpu_period_micros=args.cpu_period,
    )

    try:
        if args.action == "create":
            container.create_config()
        elif args.action == "start":
            container.start()
        elif args.action == "stop":
            container.stop()
        elif args.action == "status":
            print(container.status())
        elif args.action == "attach":
            result = container.attach(shlex.split(args.command))
            print(result.stdout or "")
            return result.returncode
    except LXCError as exc:
        print(exc, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(cli())
